var annotated_dup =
[
    [ "CNA", "namespaceCNA.html", [
      [ "Extended", "namespaceCNA_1_1Extended.html", [
        [ "Animations", "namespaceCNA_1_1Extended_1_1Animations.html", [
          [ "AnimationComponent", "classCNA_1_1Extended_1_1Animations_1_1AnimationComponent.html", "classCNA_1_1Extended_1_1Animations_1_1AnimationComponent" ],
          [ "AnimationController", "classCNA_1_1Extended_1_1Animations_1_1AnimationController.html", "classCNA_1_1Extended_1_1Animations_1_1AnimationController" ],
          [ "AnimationEvent", "classCNA_1_1Extended_1_1Animations_1_1AnimationEvent.html", "classCNA_1_1Extended_1_1Animations_1_1AnimationEvent" ],
          [ "IAnimation", "classCNA_1_1Extended_1_1Animations_1_1IAnimation.html", "classCNA_1_1Extended_1_1Animations_1_1IAnimation" ],
          [ "IAnimationController", "classCNA_1_1Extended_1_1Animations_1_1IAnimationController.html", "classCNA_1_1Extended_1_1Animations_1_1IAnimationController" ],
          [ "IAnimationFrame", "classCNA_1_1Extended_1_1Animations_1_1IAnimationFrame.html", "classCNA_1_1Extended_1_1Animations_1_1IAnimationFrame" ]
        ] ],
        [ "BitmapFonts", "namespaceCNA_1_1Extended_1_1BitmapFonts.html", [
          [ "BitmapFont", "classCNA_1_1Extended_1_1BitmapFonts_1_1BitmapFont.html", "classCNA_1_1Extended_1_1BitmapFonts_1_1BitmapFont" ],
          [ "BitmapFontCharacter", "classCNA_1_1Extended_1_1BitmapFonts_1_1BitmapFontCharacter.html", "classCNA_1_1Extended_1_1BitmapFonts_1_1BitmapFontCharacter" ]
        ] ],
        [ "Collections", "namespaceCNA_1_1Extended_1_1Collections.html", [
          [ "Bag", "classCNA_1_1Extended_1_1Collections_1_1Bag.html", "classCNA_1_1Extended_1_1Collections_1_1Bag" ],
          [ "Deque", "classCNA_1_1Extended_1_1Collections_1_1Deque.html", "classCNA_1_1Extended_1_1Collections_1_1Deque" ],
          [ "IObservableCollection", "classCNA_1_1Extended_1_1Collections_1_1IObservableCollection.html", "classCNA_1_1Extended_1_1Collections_1_1IObservableCollection" ],
          [ "IPoolable", "classCNA_1_1Extended_1_1Collections_1_1IPoolable.html", "classCNA_1_1Extended_1_1Collections_1_1IPoolable" ],
          [ "ItemEventArgs", "classCNA_1_1Extended_1_1Collections_1_1ItemEventArgs.html", "classCNA_1_1Extended_1_1Collections_1_1ItemEventArgs" ],
          [ "KeyedCollection", "classCNA_1_1Extended_1_1Collections_1_1KeyedCollection.html", "classCNA_1_1Extended_1_1Collections_1_1KeyedCollection" ],
          [ "ObjectPool", "classCNA_1_1Extended_1_1Collections_1_1ObjectPool.html", "classCNA_1_1Extended_1_1Collections_1_1ObjectPool" ],
          [ "ObservableCollection", "classCNA_1_1Extended_1_1Collections_1_1ObservableCollection.html", "classCNA_1_1Extended_1_1Collections_1_1ObservableCollection" ],
          [ "Pool", "classCNA_1_1Extended_1_1Collections_1_1Pool.html", "classCNA_1_1Extended_1_1Collections_1_1Pool" ]
        ] ],
        [ "Collisions", "namespaceCNA_1_1Extended_1_1Collisions.html", [
          [ "ActorPairKey", "structCNA_1_1Extended_1_1Collisions_1_1ActorPairKey.html", "structCNA_1_1Extended_1_1Collisions_1_1ActorPairKey" ],
          [ "CollisionEvent2D", "classCNA_1_1Extended_1_1Collisions_1_1CollisionEvent2D.html", "classCNA_1_1Extended_1_1Collisions_1_1CollisionEvent2D" ],
          [ "CollisionPair2D", "classCNA_1_1Extended_1_1Collisions_1_1CollisionPair2D.html", "classCNA_1_1Extended_1_1Collisions_1_1CollisionPair2D" ],
          [ "CollisionWorld2D", "classCNA_1_1Extended_1_1Collisions_1_1CollisionWorld2D.html", "classCNA_1_1Extended_1_1Collisions_1_1CollisionWorld2D" ],
          [ "ICollisionActor", "classCNA_1_1Extended_1_1Collisions_1_1ICollisionActor.html", "classCNA_1_1Extended_1_1Collisions_1_1ICollisionActor" ],
          [ "ICollisionBroadphase2D", "classCNA_1_1Extended_1_1Collisions_1_1ICollisionBroadphase2D.html", "classCNA_1_1Extended_1_1Collisions_1_1ICollisionBroadphase2D" ],
          [ "Layer", "classCNA_1_1Extended_1_1Collisions_1_1Layer.html", "classCNA_1_1Extended_1_1Collisions_1_1Layer" ],
          [ "LayerPair", "structCNA_1_1Extended_1_1Collisions_1_1LayerPair.html", "structCNA_1_1Extended_1_1Collisions_1_1LayerPair" ],
          [ "QuadTree", "classCNA_1_1Extended_1_1Collisions_1_1QuadTree.html", "classCNA_1_1Extended_1_1Collisions_1_1QuadTree" ],
          [ "QuadtreeData", "classCNA_1_1Extended_1_1Collisions_1_1QuadtreeData.html", "classCNA_1_1Extended_1_1Collisions_1_1QuadtreeData" ],
          [ "QuadTreeSpace", "classCNA_1_1Extended_1_1Collisions_1_1QuadTreeSpace.html", "classCNA_1_1Extended_1_1Collisions_1_1QuadTreeSpace" ],
          [ "SpatialHash", "classCNA_1_1Extended_1_1Collisions_1_1SpatialHash.html", "classCNA_1_1Extended_1_1Collisions_1_1SpatialHash" ],
          [ "SpatialHashCellKey", "structCNA_1_1Extended_1_1Collisions_1_1SpatialHashCellKey.html", "structCNA_1_1Extended_1_1Collisions_1_1SpatialHashCellKey" ],
          [ "UndefinedLayerException", "classCNA_1_1Extended_1_1Collisions_1_1UndefinedLayerException.html", "classCNA_1_1Extended_1_1Collisions_1_1UndefinedLayerException" ]
        ] ],
        [ "Content", "namespaceCNA_1_1Extended_1_1Content.html", [
          [ "BitmapFonts", "namespaceCNA_1_1Extended_1_1Content_1_1BitmapFonts.html", [
            [ "BitmapFontFileContent", "classCNA_1_1Extended_1_1Content_1_1BitmapFonts_1_1BitmapFontFileContent.html", "classCNA_1_1Extended_1_1Content_1_1BitmapFonts_1_1BitmapFontFileContent" ],
            [ "CharacterBlock", "structCNA_1_1Extended_1_1Content_1_1BitmapFonts_1_1CharacterBlock.html", "structCNA_1_1Extended_1_1Content_1_1BitmapFonts_1_1CharacterBlock" ],
            [ "CommonBlock", "structCNA_1_1Extended_1_1Content_1_1BitmapFonts_1_1CommonBlock.html", "structCNA_1_1Extended_1_1Content_1_1BitmapFonts_1_1CommonBlock" ],
            [ "HeaderBlock", "structCNA_1_1Extended_1_1Content_1_1BitmapFonts_1_1HeaderBlock.html", "structCNA_1_1Extended_1_1Content_1_1BitmapFonts_1_1HeaderBlock" ],
            [ "InfoBlock", "structCNA_1_1Extended_1_1Content_1_1BitmapFonts_1_1InfoBlock.html", "structCNA_1_1Extended_1_1Content_1_1BitmapFonts_1_1InfoBlock" ],
            [ "KerningPairsBlock", "structCNA_1_1Extended_1_1Content_1_1BitmapFonts_1_1KerningPairsBlock.html", "structCNA_1_1Extended_1_1Content_1_1BitmapFonts_1_1KerningPairsBlock" ]
          ] ],
          [ "TexturePacker", "namespaceCNA_1_1Extended_1_1Content_1_1TexturePacker.html", [
            [ "TexturePackerFileContent", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerFileContent.html", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerFileContent" ],
            [ "TexturePackerFrame", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerFrame.html", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerFrame" ],
            [ "TexturePackerMeta", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerMeta.html", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerMeta" ],
            [ "TexturePackerPoint", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerPoint.html", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerPoint" ],
            [ "TexturePackerPointF", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerPointF.html", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerPointF" ],
            [ "TexturePackerRectangle", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerRectangle.html", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerRectangle" ],
            [ "TexturePackerSize", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerSize.html", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerSize" ],
            [ "TexturePackerTexture", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerTexture.html", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerTexture" ],
            [ "TexturePackerTextureFrame", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerTextureFrame.html", "classCNA_1_1Extended_1_1Content_1_1TexturePacker_1_1TexturePackerTextureFrame" ]
          ] ],
          [ "IContentLoader", "classCNA_1_1Extended_1_1Content_1_1IContentLoader.html", "classCNA_1_1Extended_1_1Content_1_1IContentLoader" ]
        ] ],
        [ "ECS", "namespaceCNA_1_1Extended_1_1ECS.html", [
          [ "Systems", "namespaceCNA_1_1Extended_1_1ECS_1_1Systems.html", [
            [ "DrawSystem", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1DrawSystem.html", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1DrawSystem" ],
            [ "EntityDrawSystem", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1EntityDrawSystem.html", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1EntityDrawSystem" ],
            [ "EntityProcessingSystem", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1EntityProcessingSystem.html", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1EntityProcessingSystem" ],
            [ "EntitySystem", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1EntitySystem.html", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1EntitySystem" ],
            [ "EntityUpdateSystem", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1EntityUpdateSystem.html", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1EntityUpdateSystem" ],
            [ "IDrawSystem", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1IDrawSystem.html", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1IDrawSystem" ],
            [ "ISystem", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1ISystem.html", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1ISystem" ],
            [ "IUpdateSystem", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1IUpdateSystem.html", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1IUpdateSystem" ],
            [ "UpdateSystem", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1UpdateSystem.html", "classCNA_1_1Extended_1_1ECS_1_1Systems_1_1UpdateSystem" ]
          ] ],
          [ "Aspect", "classCNA_1_1Extended_1_1ECS_1_1Aspect.html", "classCNA_1_1Extended_1_1ECS_1_1Aspect" ],
          [ "AspectBuilder", "classCNA_1_1Extended_1_1ECS_1_1AspectBuilder.html", "classCNA_1_1Extended_1_1ECS_1_1AspectBuilder" ],
          [ "ComponentBits", "classCNA_1_1Extended_1_1ECS_1_1ComponentBits.html", "classCNA_1_1Extended_1_1ECS_1_1ComponentBits" ],
          [ "ComponentManager", "classCNA_1_1Extended_1_1ECS_1_1ComponentManager.html", "classCNA_1_1Extended_1_1ECS_1_1ComponentManager" ],
          [ "ComponentMapper", "classCNA_1_1Extended_1_1ECS_1_1ComponentMapper.html", "classCNA_1_1Extended_1_1ECS_1_1ComponentMapper" ],
          [ "ComponentMapperOf", "classCNA_1_1Extended_1_1ECS_1_1ComponentMapperOf.html", "classCNA_1_1Extended_1_1ECS_1_1ComponentMapperOf" ],
          [ "Entity", "classCNA_1_1Extended_1_1ECS_1_1Entity.html", "classCNA_1_1Extended_1_1ECS_1_1Entity" ],
          [ "EntityManager", "classCNA_1_1Extended_1_1ECS_1_1EntityManager.html", "classCNA_1_1Extended_1_1ECS_1_1EntityManager" ],
          [ "EntitySubscription", "classCNA_1_1Extended_1_1ECS_1_1EntitySubscription.html", "classCNA_1_1Extended_1_1ECS_1_1EntitySubscription" ],
          [ "World", "classCNA_1_1Extended_1_1ECS_1_1World.html", "classCNA_1_1Extended_1_1ECS_1_1World" ],
          [ "WorldBuilder", "classCNA_1_1Extended_1_1ECS_1_1WorldBuilder.html", "classCNA_1_1Extended_1_1ECS_1_1WorldBuilder" ]
        ] ],
        [ "Graphics", "namespaceCNA_1_1Extended_1_1Graphics.html", [
          [ "Effects", "namespaceCNA_1_1Extended_1_1Graphics_1_1Effects.html", [
            [ "DefaultEffect", "classCNA_1_1Extended_1_1Graphics_1_1Effects_1_1DefaultEffect.html", "classCNA_1_1Extended_1_1Graphics_1_1Effects_1_1DefaultEffect" ],
            [ "ITextureEffect", "classCNA_1_1Extended_1_1Graphics_1_1Effects_1_1ITextureEffect.html", "classCNA_1_1Extended_1_1Graphics_1_1Effects_1_1ITextureEffect" ],
            [ "MatrixChainEffect", "classCNA_1_1Extended_1_1Graphics_1_1Effects_1_1MatrixChainEffect.html", "classCNA_1_1Extended_1_1Graphics_1_1Effects_1_1MatrixChainEffect" ]
          ] ],
          [ "AnimatedSprite", "classCNA_1_1Extended_1_1Graphics_1_1AnimatedSprite.html", "classCNA_1_1Extended_1_1Graphics_1_1AnimatedSprite" ],
          [ "IMatrixChainEffect", "classCNA_1_1Extended_1_1Graphics_1_1IMatrixChainEffect.html", "classCNA_1_1Extended_1_1Graphics_1_1IMatrixChainEffect" ],
          [ "NinePatch", "classCNA_1_1Extended_1_1Graphics_1_1NinePatch.html", "classCNA_1_1Extended_1_1Graphics_1_1NinePatch" ],
          [ "RenderTarget2DOperation", "classCNA_1_1Extended_1_1Graphics_1_1RenderTarget2DOperation.html", "classCNA_1_1Extended_1_1Graphics_1_1RenderTarget2DOperation" ],
          [ "Sprite", "classCNA_1_1Extended_1_1Graphics_1_1Sprite.html", "classCNA_1_1Extended_1_1Graphics_1_1Sprite" ],
          [ "SpriteSheet", "classCNA_1_1Extended_1_1Graphics_1_1SpriteSheet.html", "classCNA_1_1Extended_1_1Graphics_1_1SpriteSheet" ],
          [ "SpriteSheetAnimation", "classCNA_1_1Extended_1_1Graphics_1_1SpriteSheetAnimation.html", "classCNA_1_1Extended_1_1Graphics_1_1SpriteSheetAnimation" ],
          [ "SpriteSheetAnimationBuilder", "classCNA_1_1Extended_1_1Graphics_1_1SpriteSheetAnimationBuilder.html", "classCNA_1_1Extended_1_1Graphics_1_1SpriteSheetAnimationBuilder" ],
          [ "SpriteSheetAnimationFrame", "classCNA_1_1Extended_1_1Graphics_1_1SpriteSheetAnimationFrame.html", "classCNA_1_1Extended_1_1Graphics_1_1SpriteSheetAnimationFrame" ],
          [ "Texture2DAtlas", "classCNA_1_1Extended_1_1Graphics_1_1Texture2DAtlas.html", "classCNA_1_1Extended_1_1Graphics_1_1Texture2DAtlas" ],
          [ "Texture2DRegion", "classCNA_1_1Extended_1_1Graphics_1_1Texture2DRegion.html", "classCNA_1_1Extended_1_1Graphics_1_1Texture2DRegion" ]
        ] ],
        [ "Input", "namespaceCNA_1_1Extended_1_1Input.html", [
          [ "InputListeners", "namespaceCNA_1_1Extended_1_1Input_1_1InputListeners.html", [
            [ "GamePadEventArgs", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1GamePadEventArgs.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1GamePadEventArgs" ],
            [ "GamePadListener", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1GamePadListener.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1GamePadListener" ],
            [ "GamePadListenerSettings", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1GamePadListenerSettings.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1GamePadListenerSettings" ],
            [ "IInputService", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1IInputService.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1IInputService" ],
            [ "InputListener", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1InputListener.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1InputListener" ],
            [ "InputListenerComponent", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1InputListenerComponent.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1InputListenerComponent" ],
            [ "InputListenerSettings", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1InputListenerSettings.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1InputListenerSettings" ],
            [ "KeyboardEventArgs", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1KeyboardEventArgs.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1KeyboardEventArgs" ],
            [ "KeyboardListener", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1KeyboardListener.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1KeyboardListener" ],
            [ "KeyboardListenerSettings", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1KeyboardListenerSettings.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1KeyboardListenerSettings" ],
            [ "MouseEventArgs", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1MouseEventArgs.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1MouseEventArgs" ],
            [ "MouseListener", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1MouseListener.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1MouseListener" ],
            [ "MouseListenerSettings", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1MouseListenerSettings.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1MouseListenerSettings" ],
            [ "TouchEventArgs", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1TouchEventArgs.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1TouchEventArgs" ],
            [ "TouchListener", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1TouchListener.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1TouchListener" ],
            [ "TouchListenerSettings", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1TouchListenerSettings.html", "classCNA_1_1Extended_1_1Input_1_1InputListeners_1_1TouchListenerSettings" ]
          ] ],
          [ "KeyboardExtended", "classCNA_1_1Extended_1_1Input_1_1KeyboardExtended.html", "classCNA_1_1Extended_1_1Input_1_1KeyboardExtended" ],
          [ "KeyboardStateExtended", "structCNA_1_1Extended_1_1Input_1_1KeyboardStateExtended.html", "structCNA_1_1Extended_1_1Input_1_1KeyboardStateExtended" ],
          [ "MouseExtended", "classCNA_1_1Extended_1_1Input_1_1MouseExtended.html", "classCNA_1_1Extended_1_1Input_1_1MouseExtended" ],
          [ "MouseStateExtended", "structCNA_1_1Extended_1_1Input_1_1MouseStateExtended.html", "structCNA_1_1Extended_1_1Input_1_1MouseStateExtended" ]
        ] ],
        [ "Particles", "namespaceCNA_1_1Extended_1_1Particles.html", [
          [ "Data", "namespaceCNA_1_1Extended_1_1Particles_1_1Data.html", [
            [ "Particle", "structCNA_1_1Extended_1_1Particles_1_1Data_1_1Particle.html", "structCNA_1_1Extended_1_1Particles_1_1Data_1_1Particle" ],
            [ "ParticleColorParameter", "structCNA_1_1Extended_1_1Particles_1_1Data_1_1ParticleColorParameter.html", "structCNA_1_1Extended_1_1Particles_1_1Data_1_1ParticleColorParameter" ],
            [ "ParticleFloatParameter", "structCNA_1_1Extended_1_1Particles_1_1Data_1_1ParticleFloatParameter.html", "structCNA_1_1Extended_1_1Particles_1_1Data_1_1ParticleFloatParameter" ],
            [ "ParticleInt32Parameter", "structCNA_1_1Extended_1_1Particles_1_1Data_1_1ParticleInt32Parameter.html", "structCNA_1_1Extended_1_1Particles_1_1Data_1_1ParticleInt32Parameter" ],
            [ "ParticleReleaseParameters", "classCNA_1_1Extended_1_1Particles_1_1Data_1_1ParticleReleaseParameters.html", "classCNA_1_1Extended_1_1Particles_1_1Data_1_1ParticleReleaseParameters" ],
            [ "ParticleVector2Parameter", "structCNA_1_1Extended_1_1Particles_1_1Data_1_1ParticleVector2Parameter.html", "structCNA_1_1Extended_1_1Particles_1_1Data_1_1ParticleVector2Parameter" ]
          ] ],
          [ "Modifiers", "namespaceCNA_1_1Extended_1_1Particles_1_1Modifiers.html", [
            [ "Containers", "namespaceCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Containers.html", [
              [ "CircleContainerModifier", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Containers_1_1CircleContainerModifier.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Containers_1_1CircleContainerModifier" ],
              [ "RectangleContainerModifier", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Containers_1_1RectangleContainerModifier.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Containers_1_1RectangleContainerModifier" ],
              [ "RectangleLoopContainerModifier", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Containers_1_1RectangleLoopContainerModifier.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Containers_1_1RectangleLoopContainerModifier" ]
            ] ],
            [ "Interpolators", "namespaceCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators.html", [
              [ "ColorInterpolator", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1ColorInterpolator.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1ColorInterpolator" ],
              [ "HueInterpolator", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1HueInterpolator.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1HueInterpolator" ],
              [ "Interpolator", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1Interpolator.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1Interpolator" ],
              [ "InterpolatorOfT", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1InterpolatorOfT.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1InterpolatorOfT" ],
              [ "OpacityInterpolator", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1OpacityInterpolator.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1OpacityInterpolator" ],
              [ "RotationInterpolator", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1RotationInterpolator.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1RotationInterpolator" ],
              [ "ScaleInterpolator", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1ScaleInterpolator.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1ScaleInterpolator" ],
              [ "VelocityInterpolator", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1VelocityInterpolator.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Interpolators_1_1VelocityInterpolator" ]
            ] ],
            [ "AgeModifier", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1AgeModifier.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1AgeModifier" ],
            [ "DragModifier", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1DragModifier.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1DragModifier" ],
            [ "LinearGravityModifier", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1LinearGravityModifier.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1LinearGravityModifier" ],
            [ "Modifier", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Modifier.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1Modifier" ],
            [ "ModifierExecutionStrategy", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1ModifierExecutionStrategy.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1ModifierExecutionStrategy" ],
            [ "OpacityFastFadeModifier", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1OpacityFastFadeModifier.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1OpacityFastFadeModifier" ],
            [ "RotationModifier", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1RotationModifier.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1RotationModifier" ],
            [ "VelocityColorModifier", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1VelocityColorModifier.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1VelocityColorModifier" ],
            [ "VelocityModifier", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1VelocityModifier.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1VelocityModifier" ],
            [ "VortexModifier", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1VortexModifier.html", "classCNA_1_1Extended_1_1Particles_1_1Modifiers_1_1VortexModifier" ]
          ] ],
          [ "Primitives", "namespaceCNA_1_1Extended_1_1Particles_1_1Primitives.html", [
            [ "LineSegment", "structCNA_1_1Extended_1_1Particles_1_1Primitives_1_1LineSegment.html", "structCNA_1_1Extended_1_1Particles_1_1Primitives_1_1LineSegment" ]
          ] ],
          [ "Profiles", "namespaceCNA_1_1Extended_1_1Particles_1_1Profiles.html", [
            [ "BoxFillProfile", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1BoxFillProfile.html", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1BoxFillProfile" ],
            [ "BoxProfile", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1BoxProfile.html", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1BoxProfile" ],
            [ "BoxUniformProfile", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1BoxUniformProfile.html", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1BoxUniformProfile" ],
            [ "CircleProfile", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1CircleProfile.html", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1CircleProfile" ],
            [ "LineProfile", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1LineProfile.html", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1LineProfile" ],
            [ "PointProfile", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1PointProfile.html", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1PointProfile" ],
            [ "Profile", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1Profile.html", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1Profile" ],
            [ "RingProfile", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1RingProfile.html", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1RingProfile" ],
            [ "SprayProfile", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1SprayProfile.html", "classCNA_1_1Extended_1_1Particles_1_1Profiles_1_1SprayProfile" ]
          ] ],
          [ "ParticleBuffer", "classCNA_1_1Extended_1_1Particles_1_1ParticleBuffer.html", "classCNA_1_1Extended_1_1Particles_1_1ParticleBuffer" ],
          [ "ParticleEffect", "classCNA_1_1Extended_1_1Particles_1_1ParticleEffect.html", "classCNA_1_1Extended_1_1Particles_1_1ParticleEffect" ],
          [ "ParticleEmitter", "classCNA_1_1Extended_1_1Particles_1_1ParticleEmitter.html", "classCNA_1_1Extended_1_1Particles_1_1ParticleEmitter" ],
          [ "ParticleIterator", "classCNA_1_1Extended_1_1Particles_1_1ParticleIterator.html", "classCNA_1_1Extended_1_1Particles_1_1ParticleIterator" ]
        ] ],
        [ "Screens", "namespaceCNA_1_1Extended_1_1Screens.html", [
          [ "Transitions", "namespaceCNA_1_1Extended_1_1Screens_1_1Transitions.html", [
            [ "ExpandTransition", "classCNA_1_1Extended_1_1Screens_1_1Transitions_1_1ExpandTransition.html", "classCNA_1_1Extended_1_1Screens_1_1Transitions_1_1ExpandTransition" ],
            [ "FadeTransition", "classCNA_1_1Extended_1_1Screens_1_1Transitions_1_1FadeTransition.html", "classCNA_1_1Extended_1_1Screens_1_1Transitions_1_1FadeTransition" ],
            [ "Transition", "classCNA_1_1Extended_1_1Screens_1_1Transitions_1_1Transition.html", "classCNA_1_1Extended_1_1Screens_1_1Transitions_1_1Transition" ]
          ] ],
          [ "GameScreen", "classCNA_1_1Extended_1_1Screens_1_1GameScreen.html", "classCNA_1_1Extended_1_1Screens_1_1GameScreen" ],
          [ "Screen", "classCNA_1_1Extended_1_1Screens_1_1Screen.html", "classCNA_1_1Extended_1_1Screens_1_1Screen" ],
          [ "ScreenManager", "classCNA_1_1Extended_1_1Screens_1_1ScreenManager.html", "classCNA_1_1Extended_1_1Screens_1_1ScreenManager" ]
        ] ],
        [ "Serialization", "namespaceCNA_1_1Extended_1_1Serialization.html", [
          [ "Json", "namespaceCNA_1_1Extended_1_1Serialization_1_1Json.html", [
            [ "ContentManagerJsonConverter", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1ContentManagerJsonConverter.html", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1ContentManagerJsonConverter" ],
            [ "ITextureRegionService", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1ITextureRegionService.html", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1ITextureRegionService" ],
            [ "JsonContentLoader", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1JsonContentLoader.html", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1JsonContentLoader" ],
            [ "NinePatchJsonConverter", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1NinePatchJsonConverter.html", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1NinePatchJsonConverter" ],
            [ "TextContentLoader", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1TextContentLoader.html", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1TextContentLoader" ],
            [ "TextureAtlasJsonConverter", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1TextureAtlasJsonConverter.html", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1TextureAtlasJsonConverter" ],
            [ "TextureRegion2DJsonConverter", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1TextureRegion2DJsonConverter.html", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1TextureRegion2DJsonConverter" ],
            [ "TextureRegionService", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1TextureRegionService.html", "classCNA_1_1Extended_1_1Serialization_1_1Json_1_1TextureRegionService" ]
          ] ]
        ] ],
        [ "Shapes", "namespaceCNA_1_1Extended_1_1Shapes.html", [
          [ "Polygon", "classCNA_1_1Extended_1_1Shapes_1_1Polygon.html", "classCNA_1_1Extended_1_1Shapes_1_1Polygon" ],
          [ "Polyline", "classCNA_1_1Extended_1_1Shapes_1_1Polyline.html", "classCNA_1_1Extended_1_1Shapes_1_1Polyline" ]
        ] ],
        [ "Tilemaps", "namespaceCNA_1_1Extended_1_1Tilemaps.html", [
          [ "LDtk", "namespaceCNA_1_1Extended_1_1Tilemaps_1_1LDtk.html", [
            [ "Document", "namespaceCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document.html", [
              [ "LDtkAutoLayerRule", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkAutoLayerRule.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkAutoLayerRule" ],
              [ "LDtkAutoLayerRuleGroup", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkAutoLayerRuleGroup.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkAutoLayerRuleGroup" ],
              [ "LDtkDefinitions", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkDefinitions.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkDefinitions" ],
              [ "LDtkEntityDefinition", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkEntityDefinition.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkEntityDefinition" ],
              [ "LDtkEntityInstance", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkEntityInstance.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkEntityInstance" ],
              [ "LDtkEntityReferenceInfos", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkEntityReferenceInfos.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkEntityReferenceInfos" ],
              [ "LDtkEnumDefinition", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkEnumDefinition.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkEnumDefinition" ],
              [ "LDtkEnumValue", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkEnumValue.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkEnumValue" ],
              [ "LDtkFieldDefinition", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkFieldDefinition.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkFieldDefinition" ],
              [ "LDtkFieldInstance", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkFieldInstance.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkFieldInstance" ],
              [ "LDtkGridPoint", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkGridPoint.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkGridPoint" ],
              [ "LDtkIntGridValueDefinition", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkIntGridValueDefinition.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkIntGridValueDefinition" ],
              [ "LDtkLayerDefinition", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkLayerDefinition.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkLayerDefinition" ],
              [ "LDtkLayerInstance", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkLayerInstance.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkLayerInstance" ],
              [ "LDtkLevel", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkLevel.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkLevel" ],
              [ "LDtkNeighbourLevel", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkNeighbourLevel.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkNeighbourLevel" ],
              [ "LDtkProject", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkProject.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkProject" ],
              [ "LDtkTableOfContentEntry", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkTableOfContentEntry.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkTableOfContentEntry" ],
              [ "LDtkTileInstance", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkTileInstance.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkTileInstance" ],
              [ "LDtkTilesetDefinition", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkTilesetDefinition.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkTilesetDefinition" ],
              [ "LDtkTocInstanceData", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkTocInstanceData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkTocInstanceData" ],
              [ "LDtkWorld", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkWorld.html", "structCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1Document_1_1LDtkWorld" ]
            ] ],
            [ "LDtkJsonParser", "classCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1LDtkJsonParser.html", "classCNA_1_1Extended_1_1Tilemaps_1_1LDtk_1_1LDtkJsonParser" ]
          ] ],
          [ "Ogmo", "namespaceCNA_1_1Extended_1_1Tilemaps_1_1Ogmo.html", [
            [ "Document", "namespaceCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document.html", [
              [ "OgmoDecal", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoDecal.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoDecal" ],
              [ "OgmoDecalLayerData", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoDecalLayerData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoDecalLayerData" ],
              [ "OgmoEntity", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoEntity.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoEntity" ],
              [ "OgmoEntityLayerData", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoEntityLayerData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoEntityLayerData" ],
              [ "OgmoEntityTemplate", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoEntityTemplate.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoEntityTemplate" ],
              [ "OgmoGridLayerData", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoGridLayerData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoGridLayerData" ],
              [ "OgmoLayerData", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoLayerData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoLayerData" ],
              [ "OgmoLayerTemplate", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoLayerTemplate.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoLayerTemplate" ],
              [ "OgmoLevel", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoLevel.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoLevel" ],
              [ "OgmoProject", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoProject.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoProject" ],
              [ "OgmoShape", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoShape.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoShape" ],
              [ "OgmoTileLayerData", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoTileLayerData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoTileLayerData" ],
              [ "OgmoTilesetTemplate", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoTilesetTemplate.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoTilesetTemplate" ],
              [ "OgmoValueTemplate", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoValueTemplate.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoValueTemplate" ],
              [ "OgmoVector2", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoVector2.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1Document_1_1OgmoVector2" ]
            ] ],
            [ "OgmoJsonParser", "classCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1OgmoJsonParser.html", "classCNA_1_1Extended_1_1Tilemaps_1_1Ogmo_1_1OgmoJsonParser" ]
          ] ],
          [ "Parsers", "namespaceCNA_1_1Extended_1_1Tilemaps_1_1Parsers.html", [
            [ "ITilemapParser", "classCNA_1_1Extended_1_1Tilemaps_1_1Parsers_1_1ITilemapParser.html", "classCNA_1_1Extended_1_1Tilemaps_1_1Parsers_1_1ITilemapParser" ],
            [ "TilemapParseException", "classCNA_1_1Extended_1_1Tilemaps_1_1Parsers_1_1TilemapParseException.html", "classCNA_1_1Extended_1_1Tilemaps_1_1Parsers_1_1TilemapParseException" ]
          ] ],
          [ "Rendering", "namespaceCNA_1_1Extended_1_1Tilemaps_1_1Rendering.html", [
            [ "LayerModel", "classCNA_1_1Extended_1_1Tilemaps_1_1Rendering_1_1LayerModel.html", "classCNA_1_1Extended_1_1Tilemaps_1_1Rendering_1_1LayerModel" ],
            [ "TilemapRenderer", "classCNA_1_1Extended_1_1Tilemaps_1_1Rendering_1_1TilemapRenderer.html", "classCNA_1_1Extended_1_1Tilemaps_1_1Rendering_1_1TilemapRenderer" ],
            [ "TilemapSpriteBatchRenderer", "classCNA_1_1Extended_1_1Tilemaps_1_1Rendering_1_1TilemapSpriteBatchRenderer.html", "classCNA_1_1Extended_1_1Tilemaps_1_1Rendering_1_1TilemapSpriteBatchRenderer" ],
            [ "TilemapWorldRenderer", "classCNA_1_1Extended_1_1Tilemaps_1_1Rendering_1_1TilemapWorldRenderer.html", "classCNA_1_1Extended_1_1Tilemaps_1_1Rendering_1_1TilemapWorldRenderer" ],
            [ "TilemapWorldSpriteBatchRenderer", "classCNA_1_1Extended_1_1Tilemaps_1_1Rendering_1_1TilemapWorldSpriteBatchRenderer.html", "classCNA_1_1Extended_1_1Tilemaps_1_1Rendering_1_1TilemapWorldSpriteBatchRenderer" ]
          ] ],
          [ "Tiled", "namespaceCNA_1_1Extended_1_1Tilemaps_1_1Tiled.html", [
            [ "Document", "namespaceCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document.html", [
              [ "TiledAnimationFrameXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledAnimationFrameXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledAnimationFrameXml" ],
              [ "TiledAnimationXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledAnimationXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledAnimationXml" ],
              [ "TiledChunkXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledChunkXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledChunkXml" ],
              [ "TiledDataTileXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledDataTileXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledDataTileXml" ],
              [ "TiledEllipseXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledEllipseXml.html", null ],
              [ "TiledGridXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledGridXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledGridXml" ],
              [ "TiledGroupLayerXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledGroupLayerXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledGroupLayerXml" ],
              [ "TiledImageLayerXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledImageLayerXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledImageLayerXml" ],
              [ "TiledImageXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledImageXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledImageXml" ],
              [ "TiledLayerXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledLayerXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledLayerXml" ],
              [ "TiledMapXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledMapXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledMapXml" ],
              [ "TiledObjectGroupXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledObjectGroupXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledObjectGroupXml" ],
              [ "TiledObjectLayerXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledObjectLayerXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledObjectLayerXml" ],
              [ "TiledObjectXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledObjectXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledObjectXml" ],
              [ "TiledPointXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledPointXml.html", null ],
              [ "TiledPolygonXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledPolygonXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledPolygonXml" ],
              [ "TiledPolylineXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledPolylineXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledPolylineXml" ],
              [ "TiledPropertiesXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledPropertiesXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledPropertiesXml" ],
              [ "TiledPropertyXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledPropertyXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledPropertyXml" ],
              [ "TiledTextXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTextXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTextXml" ],
              [ "TiledTileLayerDataXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTileLayerDataXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTileLayerDataXml" ],
              [ "TiledTileLayerXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTileLayerXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTileLayerXml" ],
              [ "TiledTileOffsetXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTileOffsetXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTileOffsetXml" ],
              [ "TiledTilesetRefXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTilesetRefXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTilesetRefXml" ],
              [ "TiledTilesetXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTilesetXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTilesetXml" ],
              [ "TiledTileXml", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTileXml.html", "structCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1Document_1_1TiledTileXml" ]
            ] ],
            [ "TiledTmxParser", "classCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1TiledTmxParser.html", "classCNA_1_1Extended_1_1Tilemaps_1_1Tiled_1_1TiledTmxParser" ]
          ] ],
          [ "Tilemap", "classCNA_1_1Extended_1_1Tilemaps_1_1Tilemap.html", "classCNA_1_1Extended_1_1Tilemaps_1_1Tilemap" ],
          [ "TilemapAnimationData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapAnimationData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapAnimationData" ],
          [ "TilemapAnimationFrameData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapAnimationFrameData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapAnimationFrameData" ],
          [ "TilemapData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapData" ],
          [ "TilemapDataLayer", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapDataLayer.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapDataLayer" ],
          [ "TilemapDataLayerData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapDataLayerData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapDataLayerData" ],
          [ "TilemapDecodedTile", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapDecodedTile.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapDecodedTile" ],
          [ "TilemapEllipseObject", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapEllipseObject.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapEllipseObject" ],
          [ "TilemapEllipseObjectData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapEllipseObjectData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapEllipseObjectData" ],
          [ "TilemapGroupLayer", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapGroupLayer.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapGroupLayer" ],
          [ "TilemapGroupLayerData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapGroupLayerData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapGroupLayerData" ],
          [ "TilemapImageLayer", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapImageLayer.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapImageLayer" ],
          [ "TilemapImageLayerData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapImageLayerData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapImageLayerData" ],
          [ "TilemapLayer", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapLayer.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapLayer" ],
          [ "TilemapLayerCollection", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapLayerCollection.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapLayerCollection" ],
          [ "TilemapLayerData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapLayerData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapLayerData" ],
          [ "TilemapObject", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapObject.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapObject" ],
          [ "TilemapObjectData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapObjectData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapObjectData" ],
          [ "TilemapObjectLayer", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapObjectLayer.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapObjectLayer" ],
          [ "TilemapObjectLayerData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapObjectLayerData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapObjectLayerData" ],
          [ "TilemapPointObject", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapPointObject.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapPointObject" ],
          [ "TilemapPointObjectData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapPointObjectData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapPointObjectData" ],
          [ "TilemapPolygonObject", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapPolygonObject.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapPolygonObject" ],
          [ "TilemapPolygonObjectData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapPolygonObjectData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapPolygonObjectData" ],
          [ "TilemapPolylineObject", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapPolylineObject.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapPolylineObject" ],
          [ "TilemapPolylineObjectData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapPolylineObjectData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapPolylineObjectData" ],
          [ "TilemapProperties", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapProperties.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapProperties" ],
          [ "TilemapPropertyData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapPropertyData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapPropertyData" ],
          [ "TilemapPropertyValue", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapPropertyValue.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapPropertyValue" ],
          [ "TilemapRectangleObject", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapRectangleObject.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapRectangleObject" ],
          [ "TilemapRectangleObjectData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapRectangleObjectData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapRectangleObjectData" ],
          [ "TilemapTextObject", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTextObject.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTextObject" ],
          [ "TilemapTextObjectData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTextObjectData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTextObjectData" ],
          [ "TilemapTile", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTile.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTile" ],
          [ "TilemapTileAnimation", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileAnimation.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileAnimation" ],
          [ "TilemapTileAnimationFrame", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileAnimationFrame.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileAnimationFrame" ],
          [ "TilemapTileData", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileData.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileData" ],
          [ "TilemapTileEntry", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileEntry.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileEntry" ],
          [ "TilemapTileEntryData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileEntryData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileEntryData" ],
          [ "TilemapTileLayer", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileLayer.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileLayer" ],
          [ "TilemapTileLayerData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileLayerData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileLayerData" ],
          [ "TilemapTileObject", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileObject.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileObject" ],
          [ "TilemapTileObjectData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileObjectData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileObjectData" ],
          [ "TilemapTileset", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileset.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTileset" ],
          [ "TilemapTilesetCollection", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTilesetCollection.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapTilesetCollection" ],
          [ "TilemapTilesetData", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTilesetData.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTilesetData" ],
          [ "TilemapTilesetEntry", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTilesetEntry.html", "structCNA_1_1Extended_1_1Tilemaps_1_1TilemapTilesetEntry" ],
          [ "TilemapWorld", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapWorld.html", "classCNA_1_1Extended_1_1Tilemaps_1_1TilemapWorld" ]
        ] ],
        [ "Timers", "namespaceCNA_1_1Extended_1_1Timers.html", [
          [ "ContinuousClock", "classCNA_1_1Extended_1_1Timers_1_1ContinuousClock.html", "classCNA_1_1Extended_1_1Timers_1_1ContinuousClock" ],
          [ "CountdownTimer", "classCNA_1_1Extended_1_1Timers_1_1CountdownTimer.html", "classCNA_1_1Extended_1_1Timers_1_1CountdownTimer" ],
          [ "GameTimer", "classCNA_1_1Extended_1_1Timers_1_1GameTimer.html", "classCNA_1_1Extended_1_1Timers_1_1GameTimer" ]
        ] ],
        [ "Triangulation", "namespaceCNA_1_1Extended_1_1Triangulation.html", [
          [ "CyclicalList", "classCNA_1_1Extended_1_1Triangulation_1_1CyclicalList.html", "classCNA_1_1Extended_1_1Triangulation_1_1CyclicalList" ],
          [ "IndexableCyclicalLinkedList", "classCNA_1_1Extended_1_1Triangulation_1_1IndexableCyclicalLinkedList.html", "classCNA_1_1Extended_1_1Triangulation_1_1IndexableCyclicalLinkedList" ],
          [ "LineSegment", "structCNA_1_1Extended_1_1Triangulation_1_1LineSegment.html", "structCNA_1_1Extended_1_1Triangulation_1_1LineSegment" ],
          [ "Triangle", "structCNA_1_1Extended_1_1Triangulation_1_1Triangle.html", "structCNA_1_1Extended_1_1Triangulation_1_1Triangle" ],
          [ "Triangulator", "classCNA_1_1Extended_1_1Triangulation_1_1Triangulator.html", "classCNA_1_1Extended_1_1Triangulation_1_1Triangulator" ],
          [ "Vertex", "structCNA_1_1Extended_1_1Triangulation_1_1Vertex.html", "structCNA_1_1Extended_1_1Triangulation_1_1Vertex" ]
        ] ],
        [ "Tweening", "namespaceCNA_1_1Extended_1_1Tweening.html", [
          [ "ColorTween", "classCNA_1_1Extended_1_1Tweening_1_1ColorTween.html", "classCNA_1_1Extended_1_1Tweening_1_1ColorTween" ],
          [ "EasingFunctions", "classCNA_1_1Extended_1_1Tweening_1_1EasingFunctions.html", "classCNA_1_1Extended_1_1Tweening_1_1EasingFunctions" ],
          [ "LinearTween", "classCNA_1_1Extended_1_1Tweening_1_1LinearTween.html", "classCNA_1_1Extended_1_1Tweening_1_1LinearTween" ],
          [ "Tween", "classCNA_1_1Extended_1_1Tweening_1_1Tween.html", "classCNA_1_1Extended_1_1Tweening_1_1Tween" ],
          [ "Tweener", "classCNA_1_1Extended_1_1Tweening_1_1Tweener.html", "classCNA_1_1Extended_1_1Tweening_1_1Tweener" ],
          [ "TweenMember", "classCNA_1_1Extended_1_1Tweening_1_1TweenMember.html", "classCNA_1_1Extended_1_1Tweening_1_1TweenMember" ],
          [ "TypedTween", "classCNA_1_1Extended_1_1Tweening_1_1TypedTween.html", "classCNA_1_1Extended_1_1Tweening_1_1TypedTween" ]
        ] ],
        [ "VectorDraw", "namespaceCNA_1_1Extended_1_1VectorDraw.html", [
          [ "PrimitiveBatch", "classCNA_1_1Extended_1_1VectorDraw_1_1PrimitiveBatch.html", "classCNA_1_1Extended_1_1VectorDraw_1_1PrimitiveBatch" ],
          [ "PrimitiveDrawing", "classCNA_1_1Extended_1_1VectorDraw_1_1PrimitiveDrawing.html", "classCNA_1_1Extended_1_1VectorDraw_1_1PrimitiveDrawing" ]
        ] ],
        [ "ViewportAdapters", "namespaceCNA_1_1Extended_1_1ViewportAdapters.html", [
          [ "BoxingViewportAdapter", "classCNA_1_1Extended_1_1ViewportAdapters_1_1BoxingViewportAdapter.html", "classCNA_1_1Extended_1_1ViewportAdapters_1_1BoxingViewportAdapter" ],
          [ "DefaultViewportAdapter", "classCNA_1_1Extended_1_1ViewportAdapters_1_1DefaultViewportAdapter.html", "classCNA_1_1Extended_1_1ViewportAdapters_1_1DefaultViewportAdapter" ],
          [ "ScalingViewportAdapter", "classCNA_1_1Extended_1_1ViewportAdapters_1_1ScalingViewportAdapter.html", "classCNA_1_1Extended_1_1ViewportAdapters_1_1ScalingViewportAdapter" ],
          [ "ViewportAdapter", "classCNA_1_1Extended_1_1ViewportAdapters_1_1ViewportAdapter.html", "classCNA_1_1Extended_1_1ViewportAdapters_1_1ViewportAdapter" ],
          [ "WindowViewportAdapter", "classCNA_1_1Extended_1_1ViewportAdapters_1_1WindowViewportAdapter.html", "classCNA_1_1Extended_1_1ViewportAdapters_1_1WindowViewportAdapter" ]
        ] ],
        [ "World3DEXT", "namespaceCNA_1_1Extended_1_1World3DEXT.html", [
          [ "ActorPairKey3DEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1ActorPairKey3DEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1ActorPairKey3DEXT" ],
          [ "AgeModifier3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1AgeModifier3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1AgeModifier3DEXT" ],
          [ "AnimatedBillboardComponentEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1AnimatedBillboardComponentEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1AnimatedBillboardComponentEXT" ],
          [ "AnimatedBillboardSystemEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1AnimatedBillboardSystemEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1AnimatedBillboardSystemEXT" ],
          [ "AnimationSystem3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1AnimationSystem3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1AnimationSystem3DEXT" ],
          [ "BillboardComponentEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1BillboardComponentEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1BillboardComponentEXT" ],
          [ "BillboardRenderSystemEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1BillboardRenderSystemEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1BillboardRenderSystemEXT" ],
          [ "BoxContainerModifier3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1BoxContainerModifier3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1BoxContainerModifier3DEXT" ],
          [ "BoxFillProfile3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1BoxFillProfile3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1BoxFillProfile3DEXT" ],
          [ "BoxLoopContainerModifier3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1BoxLoopContainerModifier3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1BoxLoopContainerModifier3DEXT" ],
          [ "BoxProfile3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1BoxProfile3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1BoxProfile3DEXT" ],
          [ "BoxUniformProfile3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1BoxUniformProfile3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1BoxUniformProfile3DEXT" ],
          [ "Camera3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1Camera3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1Camera3DEXT" ],
          [ "CircleProfile3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1CircleProfile3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1CircleProfile3DEXT" ],
          [ "CollisionEvent3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1CollisionEvent3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1CollisionEvent3DEXT" ],
          [ "CollisionPair3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1CollisionPair3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1CollisionPair3DEXT" ],
          [ "CollisionResult3DEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1CollisionResult3DEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1CollisionResult3DEXT" ],
          [ "CollisionShape3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1CollisionShape3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1CollisionShape3DEXT" ],
          [ "CollisionWorld3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1CollisionWorld3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1CollisionWorld3DEXT" ],
          [ "ColorInterpolator3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1ColorInterpolator3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1ColorInterpolator3DEXT" ],
          [ "ConeProfile3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1ConeProfile3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1ConeProfile3DEXT" ],
          [ "CubeMeshComponentEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1CubeMeshComponentEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1CubeMeshComponentEXT" ],
          [ "CubeMeshRenderSystemEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1CubeMeshRenderSystemEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1CubeMeshRenderSystemEXT" ],
          [ "DebugDrawComponentEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1DebugDrawComponentEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1DebugDrawComponentEXT" ],
          [ "DebugDrawSystemEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1DebugDrawSystemEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1DebugDrawSystemEXT" ],
          [ "DebugLineEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1DebugLineEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1DebugLineEXT" ],
          [ "DragModifier3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1DragModifier3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1DragModifier3DEXT" ],
          [ "HueInterpolator3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1HueInterpolator3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1HueInterpolator3DEXT" ],
          [ "ICollisionActor3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1ICollisionActor3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1ICollisionActor3DEXT" ],
          [ "ICollisionBroadphase3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1ICollisionBroadphase3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1ICollisionBroadphase3DEXT" ],
          [ "Interpolator3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1Interpolator3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1Interpolator3DEXT" ],
          [ "InterpolatorOfT3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1InterpolatorOfT3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1InterpolatorOfT3DEXT" ],
          [ "Layer3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1Layer3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1Layer3DEXT" ],
          [ "LayerPair3DEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1LayerPair3DEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1LayerPair3DEXT" ],
          [ "LinearGravityModifier3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1LinearGravityModifier3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1LinearGravityModifier3DEXT" ],
          [ "LineProfile3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1LineProfile3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1LineProfile3DEXT" ],
          [ "ModelComponentEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1ModelComponentEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1ModelComponentEXT" ],
          [ "Modifier3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1Modifier3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1Modifier3DEXT" ],
          [ "ModifierExecutionStrategy3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1ModifierExecutionStrategy3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1ModifierExecutionStrategy3DEXT" ],
          [ "Octree3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1Octree3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1Octree3DEXT" ],
          [ "OctreeNode3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1OctreeNode3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1OctreeNode3DEXT" ],
          [ "OctreeNodeData3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1OctreeNodeData3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1OctreeNodeData3DEXT" ],
          [ "OpacityFastFadeModifier3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1OpacityFastFadeModifier3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1OpacityFastFadeModifier3DEXT" ],
          [ "OpacityInterpolator3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1OpacityInterpolator3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1OpacityInterpolator3DEXT" ],
          [ "Particle3DEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1Particle3DEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1Particle3DEXT" ],
          [ "ParticleEffect3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1ParticleEffect3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1ParticleEffect3DEXT" ],
          [ "ParticleEffectComponentEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1ParticleEffectComponentEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1ParticleEffectComponentEXT" ],
          [ "ParticleEmitter3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1ParticleEmitter3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1ParticleEmitter3DEXT" ],
          [ "ParticleRenderSystem3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1ParticleRenderSystem3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1ParticleRenderSystem3DEXT" ],
          [ "ParticleUpdateSystem3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1ParticleUpdateSystem3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1ParticleUpdateSystem3DEXT" ],
          [ "PointProfile3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1PointProfile3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1PointProfile3DEXT" ],
          [ "Profile3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1Profile3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1Profile3DEXT" ],
          [ "RenderSystem3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1RenderSystem3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1RenderSystem3DEXT" ],
          [ "RingProfile3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1RingProfile3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1RingProfile3DEXT" ],
          [ "RotationInterpolator3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1RotationInterpolator3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1RotationInterpolator3DEXT" ],
          [ "RotationModifier3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1RotationModifier3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1RotationModifier3DEXT" ],
          [ "ScaleInterpolator3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1ScaleInterpolator3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1ScaleInterpolator3DEXT" ],
          [ "SkinnedModelComponentEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1SkinnedModelComponentEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1SkinnedModelComponentEXT" ],
          [ "SpatialHash3DCellKeyEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1SpatialHash3DCellKeyEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1SpatialHash3DCellKeyEXT" ],
          [ "SpatialHash3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1SpatialHash3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1SpatialHash3DEXT" ],
          [ "SphereContainerModifier3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1SphereContainerModifier3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1SphereContainerModifier3DEXT" ],
          [ "Text3DEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1Text3DEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1Text3DEXT" ],
          [ "Text3DMeshEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1Text3DMeshEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1Text3DMeshEXT" ],
          [ "Text3DMeshPartEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1Text3DMeshPartEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1Text3DMeshPartEXT" ],
          [ "Text3DPartEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1Text3DPartEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1Text3DPartEXT" ],
          [ "TextBillboardRenderSystemEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1TextBillboardRenderSystemEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1TextBillboardRenderSystemEXT" ],
          [ "TileCoordinate3DEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1TileCoordinate3DEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1TileCoordinate3DEXT" ],
          [ "Tilemap3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1Tilemap3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1Tilemap3DEXT" ],
          [ "Tilemap3DFactoryEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1Tilemap3DFactoryEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1Tilemap3DFactoryEXT" ],
          [ "Tilemap3DFileContent", "classCNA_1_1Extended_1_1World3DEXT_1_1Tilemap3DFileContent.html", "classCNA_1_1Extended_1_1World3DEXT_1_1Tilemap3DFileContent" ],
          [ "Tilemap3DFileTileSize", "classCNA_1_1Extended_1_1World3DEXT_1_1Tilemap3DFileTileSize.html", "classCNA_1_1Extended_1_1World3DEXT_1_1Tilemap3DFileTileSize" ],
          [ "TilemapChunkRenderer3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1TilemapChunkRenderer3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1TilemapChunkRenderer3DEXT" ],
          [ "TilemapCollisionActor3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1TilemapCollisionActor3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1TilemapCollisionActor3DEXT" ],
          [ "TilemapRenderer3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1TilemapRenderer3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1TilemapRenderer3DEXT" ],
          [ "TilemapTileset3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1TilemapTileset3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1TilemapTileset3DEXT" ],
          [ "Transform3ComponentEXT", "structCNA_1_1Extended_1_1World3DEXT_1_1Transform3ComponentEXT.html", "structCNA_1_1Extended_1_1World3DEXT_1_1Transform3ComponentEXT" ],
          [ "TransformHierarchySystemEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1TransformHierarchySystemEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1TransformHierarchySystemEXT" ],
          [ "VelocityColorModifier3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1VelocityColorModifier3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1VelocityColorModifier3DEXT" ],
          [ "VelocityInterpolator3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1VelocityInterpolator3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1VelocityInterpolator3DEXT" ],
          [ "VelocityModifier3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1VelocityModifier3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1VelocityModifier3DEXT" ],
          [ "VortexModifier3DEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1VortexModifier3DEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1VortexModifier3DEXT" ],
          [ "World3DScreenEXT", "classCNA_1_1Extended_1_1World3DEXT_1_1World3DScreenEXT.html", "classCNA_1_1Extended_1_1World3DEXT_1_1World3DScreenEXT" ]
        ] ],
        [ "Angle", "classCNA_1_1Extended_1_1Angle.html", "classCNA_1_1Extended_1_1Angle" ],
        [ "BaseTransform", "classCNA_1_1Extended_1_1BaseTransform.html", "classCNA_1_1Extended_1_1BaseTransform" ],
        [ "BoundingBox2D", "structCNA_1_1Extended_1_1BoundingBox2D.html", "structCNA_1_1Extended_1_1BoundingBox2D" ],
        [ "BoundingCapsule2D", "structCNA_1_1Extended_1_1BoundingCapsule2D.html", "structCNA_1_1Extended_1_1BoundingCapsule2D" ],
        [ "BoundingCircle2D", "structCNA_1_1Extended_1_1BoundingCircle2D.html", "structCNA_1_1Extended_1_1BoundingCircle2D" ],
        [ "BoundingPolygon2D", "structCNA_1_1Extended_1_1BoundingPolygon2D.html", "structCNA_1_1Extended_1_1BoundingPolygon2D" ],
        [ "BoundingRectangle", "structCNA_1_1Extended_1_1BoundingRectangle.html", "structCNA_1_1Extended_1_1BoundingRectangle" ],
        [ "Camera", "classCNA_1_1Extended_1_1Camera.html", "classCNA_1_1Extended_1_1Camera" ],
        [ "CircleF", "structCNA_1_1Extended_1_1CircleF.html", "structCNA_1_1Extended_1_1CircleF" ],
        [ "Collision2D", "classCNA_1_1Extended_1_1Collision2D.html", "classCNA_1_1Extended_1_1Collision2D" ],
        [ "CollisionResult2D", "structCNA_1_1Extended_1_1CollisionResult2D.html", "structCNA_1_1Extended_1_1CollisionResult2D" ],
        [ "CollisionShape2D", "classCNA_1_1Extended_1_1CollisionShape2D.html", "classCNA_1_1Extended_1_1CollisionShape2D" ],
        [ "ColorHelper", "classCNA_1_1Extended_1_1ColorHelper.html", "classCNA_1_1Extended_1_1ColorHelper" ],
        [ "EllipseF", "structCNA_1_1Extended_1_1EllipseF.html", "structCNA_1_1Extended_1_1EllipseF" ],
        [ "FastRandom", "classCNA_1_1Extended_1_1FastRandom.html", "classCNA_1_1Extended_1_1FastRandom" ],
        [ "FloatHelper", "classCNA_1_1Extended_1_1FloatHelper.html", "classCNA_1_1Extended_1_1FloatHelper" ],
        [ "FramesPerSecondCounter", "classCNA_1_1Extended_1_1FramesPerSecondCounter.html", "classCNA_1_1Extended_1_1FramesPerSecondCounter" ],
        [ "FramesPerSecondCounterComponent", "classCNA_1_1Extended_1_1FramesPerSecondCounterComponent.html", "classCNA_1_1Extended_1_1FramesPerSecondCounterComponent" ],
        [ "HslColor", "structCNA_1_1Extended_1_1HslColor.html", "structCNA_1_1Extended_1_1HslColor" ],
        [ "IColorable", "classCNA_1_1Extended_1_1IColorable.html", "classCNA_1_1Extended_1_1IColorable" ],
        [ "IEquatableByRef", "classCNA_1_1Extended_1_1IEquatableByRef.html", "classCNA_1_1Extended_1_1IEquatableByRef" ],
        [ "IMovable", "classCNA_1_1Extended_1_1IMovable.html", "classCNA_1_1Extended_1_1IMovable" ],
        [ "Interval", "classCNA_1_1Extended_1_1Interval.html", "classCNA_1_1Extended_1_1Interval" ],
        [ "IRectangular", "classCNA_1_1Extended_1_1IRectangular.html", "classCNA_1_1Extended_1_1IRectangular" ],
        [ "IRectangularF", "classCNA_1_1Extended_1_1IRectangularF.html", "classCNA_1_1Extended_1_1IRectangularF" ],
        [ "IRotatable", "classCNA_1_1Extended_1_1IRotatable.html", "classCNA_1_1Extended_1_1IRotatable" ],
        [ "IScalable", "classCNA_1_1Extended_1_1IScalable.html", "classCNA_1_1Extended_1_1IScalable" ],
        [ "ISizable", "classCNA_1_1Extended_1_1ISizable.html", "classCNA_1_1Extended_1_1ISizable" ],
        [ "Line2D", "structCNA_1_1Extended_1_1Line2D.html", "structCNA_1_1Extended_1_1Line2D" ],
        [ "LineSegment2D", "structCNA_1_1Extended_1_1LineSegment2D.html", "structCNA_1_1Extended_1_1LineSegment2D" ],
        [ "MathExtended", "classCNA_1_1Extended_1_1MathExtended.html", "classCNA_1_1Extended_1_1MathExtended" ],
        [ "Matrix3x2", "structCNA_1_1Extended_1_1Matrix3x2.html", "structCNA_1_1Extended_1_1Matrix3x2" ],
        [ "OrientedBoundingBox2D", "structCNA_1_1Extended_1_1OrientedBoundingBox2D.html", "structCNA_1_1Extended_1_1OrientedBoundingBox2D" ],
        [ "OrientedRectangle", "structCNA_1_1Extended_1_1OrientedRectangle.html", "structCNA_1_1Extended_1_1OrientedRectangle" ],
        [ "OrientedRectangleIntersection", "structCNA_1_1Extended_1_1OrientedRectangleIntersection.html", "structCNA_1_1Extended_1_1OrientedRectangleIntersection" ],
        [ "OrthographicCamera", "classCNA_1_1Extended_1_1OrthographicCamera.html", "classCNA_1_1Extended_1_1OrthographicCamera" ],
        [ "PrimitivesHelper", "classCNA_1_1Extended_1_1PrimitivesHelper.html", "classCNA_1_1Extended_1_1PrimitivesHelper" ],
        [ "Ray2", "structCNA_1_1Extended_1_1Ray2.html", "structCNA_1_1Extended_1_1Ray2" ],
        [ "Ray2D", "structCNA_1_1Extended_1_1Ray2D.html", "structCNA_1_1Extended_1_1Ray2D" ],
        [ "RectangleF", "structCNA_1_1Extended_1_1RectangleF.html", "structCNA_1_1Extended_1_1RectangleF" ],
        [ "Segment2", "structCNA_1_1Extended_1_1Segment2.html", "structCNA_1_1Extended_1_1Segment2" ],
        [ "SimpleDrawableGameComponent", "classCNA_1_1Extended_1_1SimpleDrawableGameComponent.html", "classCNA_1_1Extended_1_1SimpleDrawableGameComponent" ],
        [ "SimpleGameComponent", "classCNA_1_1Extended_1_1SimpleGameComponent.html", "classCNA_1_1Extended_1_1SimpleGameComponent" ],
        [ "Size", "structCNA_1_1Extended_1_1Size.html", "structCNA_1_1Extended_1_1Size" ],
        [ "SizeF", "structCNA_1_1Extended_1_1SizeF.html", "structCNA_1_1Extended_1_1SizeF" ],
        [ "Thickness", "structCNA_1_1Extended_1_1Thickness.html", "structCNA_1_1Extended_1_1Thickness" ],
        [ "Transform2", "classCNA_1_1Extended_1_1Transform2.html", "classCNA_1_1Extended_1_1Transform2" ],
        [ "Transform3", "classCNA_1_1Extended_1_1Transform3.html", "classCNA_1_1Extended_1_1Transform3" ]
      ] ]
    ] ],
    [ "nlohmann", "namespacenlohmann.html", [
      [ "adl_serializer< CNA::Extended::HslColor >", "structnlohmann_1_1adl__serializer_3_01CNA_1_1Extended_1_1HslColor_01_4.html", "structnlohmann_1_1adl__serializer_3_01CNA_1_1Extended_1_1HslColor_01_4" ],
      [ "adl_serializer< CNA::Extended::Interval< T > >", "structnlohmann_1_1adl__serializer_3_01CNA_1_1Extended_1_1Interval_3_01T_01_4_01_4.html", "structnlohmann_1_1adl__serializer_3_01CNA_1_1Extended_1_1Interval_3_01T_01_4_01_4" ],
      [ "adl_serializer< CNA::Extended::RectangleF >", "structnlohmann_1_1adl__serializer_3_01CNA_1_1Extended_1_1RectangleF_01_4.html", "structnlohmann_1_1adl__serializer_3_01CNA_1_1Extended_1_1RectangleF_01_4" ],
      [ "adl_serializer< CNA::Extended::Size >", "structnlohmann_1_1adl__serializer_3_01CNA_1_1Extended_1_1Size_01_4.html", "structnlohmann_1_1adl__serializer_3_01CNA_1_1Extended_1_1Size_01_4" ],
      [ "adl_serializer< CNA::Extended::SizeF >", "structnlohmann_1_1adl__serializer_3_01CNA_1_1Extended_1_1SizeF_01_4.html", "structnlohmann_1_1adl__serializer_3_01CNA_1_1Extended_1_1SizeF_01_4" ],
      [ "adl_serializer< CNA::Extended::Thickness >", "structnlohmann_1_1adl__serializer_3_01CNA_1_1Extended_1_1Thickness_01_4.html", "structnlohmann_1_1adl__serializer_3_01CNA_1_1Extended_1_1Thickness_01_4" ],
      [ "adl_serializer< Microsoft::Xna::Framework::Color >", "structnlohmann_1_1adl__serializer_3_01Microsoft_1_1Xna_1_1Framework_1_1Color_01_4.html", "structnlohmann_1_1adl__serializer_3_01Microsoft_1_1Xna_1_1Framework_1_1Color_01_4" ],
      [ "adl_serializer< Microsoft::Xna::Framework::Vector2 >", "structnlohmann_1_1adl__serializer_3_01Microsoft_1_1Xna_1_1Framework_1_1Vector2_01_4.html", "structnlohmann_1_1adl__serializer_3_01Microsoft_1_1Xna_1_1Framework_1_1Vector2_01_4" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< CNA::Extended::Collisions::ActorPairKey >", "structstd_1_1hash_3_01CNA_1_1Extended_1_1Collisions_1_1ActorPairKey_01_4.html", "structstd_1_1hash_3_01CNA_1_1Extended_1_1Collisions_1_1ActorPairKey_01_4" ],
      [ "hash< CNA::Extended::Collisions::LayerPair >", "structstd_1_1hash_3_01CNA_1_1Extended_1_1Collisions_1_1LayerPair_01_4.html", "structstd_1_1hash_3_01CNA_1_1Extended_1_1Collisions_1_1LayerPair_01_4" ],
      [ "hash< CNA::Extended::Collisions::SpatialHashCellKey >", "structstd_1_1hash_3_01CNA_1_1Extended_1_1Collisions_1_1SpatialHashCellKey_01_4.html", "structstd_1_1hash_3_01CNA_1_1Extended_1_1Collisions_1_1SpatialHashCellKey_01_4" ],
      [ "hash< CNA::Extended::World3DEXT::ActorPairKey3DEXT >", "structstd_1_1hash_3_01CNA_1_1Extended_1_1World3DEXT_1_1ActorPairKey3DEXT_01_4.html", "structstd_1_1hash_3_01CNA_1_1Extended_1_1World3DEXT_1_1ActorPairKey3DEXT_01_4" ],
      [ "hash< CNA::Extended::World3DEXT::LayerPair3DEXT >", "structstd_1_1hash_3_01CNA_1_1Extended_1_1World3DEXT_1_1LayerPair3DEXT_01_4.html", "structstd_1_1hash_3_01CNA_1_1Extended_1_1World3DEXT_1_1LayerPair3DEXT_01_4" ],
      [ "hash< CNA::Extended::World3DEXT::SpatialHash3DCellKeyEXT >", "structstd_1_1hash_3_01CNA_1_1Extended_1_1World3DEXT_1_1SpatialHash3DCellKeyEXT_01_4.html", "structstd_1_1hash_3_01CNA_1_1Extended_1_1World3DEXT_1_1SpatialHash3DCellKeyEXT_01_4" ],
      [ "hash< CNA::Extended::World3DEXT::TileCoordinate3DEXT >", "structstd_1_1hash_3_01CNA_1_1Extended_1_1World3DEXT_1_1TileCoordinate3DEXT_01_4.html", "structstd_1_1hash_3_01CNA_1_1Extended_1_1World3DEXT_1_1TileCoordinate3DEXT_01_4" ]
    ] ]
];